### ISSUE TITLE
Develop new class to linearize AST

### ISSUE THREAD

**Issue by Coopss** [Coopss/cse423-compiler#108]
### Issue Description
Create classes used to convert an AST into an object list

### Definition of Success
* [x] Create IR class
    - One attribute will be List\<Instruction\>
    - Methods printIR() and writeIRToFile() must be implemented later
        - Methods printList() and writeListToFile() may be optionally implemented for testing purposes
* [x] Create abstract Instruction class
    - Abstract toString() method must be overridden by subclasses
* [x] Create concrete subclasses for Instructions as follows:
    * [x] Concrete Operation class
        - Attributes consist of two operands (of class Instruction)
        - Another attribute is String operation (can be of different type, but will be used later to determine operation)
    * [x] Concrete Return class
        - No attributes
    * [x] Concrete Call class
        - Attributes consist of Instruction funcName and List\<Instruction\> paramList
        - Another attribute is Instruction returnInstruction
    * [x] Concrete Jump class
        - Attribute consists of Instruction destNodeTrue and Instruction destNodeFalse
    * [x] Concrete Identifier class
        - Attributes consist of String varType (to determine the type of the variable, and this can be numConstant) as well as String varDef (which holds the value of the variable in string format)

**Comment by mattadik123** [comment]
@Coopss, I've updated the definition of success. Let me know if that is sufficient and acceptable.
