### ISSUE TITLE
Add unit tests to token labeling

### ISSUE THREAD

**Issue by Coopss** [Coopss/cse423-compiler#18]
### Issue Description
Add comprehensive unit tests for edu.nmt.frontend.TokenLabeler

### Definition of Success
* [x]  TBD

**Comment by mattadik123** [comment]
@Coopss @RodianRomeo @tbrewerDNM can one of you review the changes made in the branch fb_#18? Thanks

**Comment by Coopss** [comment]
I'll take a look

**Comment by Coopss** [comment]
merged in #31, is this good to move into review @mattadik123
