### ISSUE TITLE
Update enum in edu.nmt.frontend.TokenLabel

### ISSUE THREAD

**Issue by tbrewerDNM** [Coopss/cse423-compiler#26]
### Issue Description
Update enum in edu.nmt.frontend.TokenLabel

### Definition of Success
* [ ]  enum updated to reflect config file

**Comment by mattadik123** [comment]
This may be resolved in #18 #29 if review is successful

**Comment by Coopss** [comment]
Resolved in https://github.com/Coopss/cse423-compiler/pull/27
