### ISSUE TITLE
Develop grammar following the features listed in the design documentation

### ISSUE THREAD

**Issue by Coopss** [Coopss/cse423-compiler#33]
### Issue Description
Develop grammar following the features listed in the design documentation

### Definition of Success
* [x] Grammar is developed
* [x] Format of the grammar is established

**Comment by Coopss** [comment]
For style I like the idea of:
```
NT
\tNT
\tNT OP T
NT
\tT
```

**Comment by tbrewerDNM** [comment]
Grammar has been completed to the best of its ability for the Monday deadline
