### ISSUE TITLE
Research about existing frameworks for parsing in Java

### ISSUE THREAD

**Issue by Coopss** [Coopss/cse423-compiler#35]
### Issue Description
Research to find a parsing tool / algorithm (preferably in Java) that we can utilize to parse the token list.
Additionally, may attempt the algorithm.

### Definition of Success
* [x] Tools / algorithm & code is found that accomplishes parsing.

**Comment by tbrewerDNM** [comment]
https://en.wikipedia.org/wiki/Canonical_LR_parser#Constructing_LR(1)_parsing_tables

Very useful source
